defaultContentLanguage = "pl"
#baseURL = "https://helipoland.com"
relativeURLs = "true"
uglyURLs = "true"

[languages]
  [languages.pl]
    weight = 1
    languageName = "Polski"
  [languages.en]
    weight = 2
    languageName = "English"
