baseURL: "https://ddrb47t0cf972.cloudfront.net"
# relativeURLs: true

defaultContentLanguage: "pl"
canonifyURLs: true

enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true

paginate: 12
title: "Helipoland.com"

params:
  siteName: "Helipoland.com"
  image: "/images/cropped-Logo-ikona-storna-270x270.jpg"
  verification:
    google: "xcAnr3n7v7u1L5SPL6DLShwWQ7l_hIATFsk7If-rI_M"
    # bing: ""
    # yandex: ""
    # pinterest: ""
    # baidu: ""

languages:
  pl:
    weight: 1
    languageCode: "pl-PL"
    languageName: "Polski"
    copyright: "© 2020, Helipoland.com. Wszelkie prawa zastrzeżone."
  en:
    weight: 2
    languageCode: "en-GB"
    languageName: "English"
    copyright: "© 2020, Helipoland.com. All rights reserved."
